package utils;

public class FinacleFieldsUtils {
	public static final String ACCOUNTSTATEMENTNONE  = "None";
	public static final String EQUATEDINSTALLMENTYES  = "yes";
	public static final String EQUATEDINSTALLMENTNO  = "no";
	public static final String INTERESTCOMPOUNDINGFREQUENCYNOCOMPOUNDING = "No Compounding";
	public static final String FREQUENCYDAILY = "Daily";
	public static final String FREQUENCYWEEKLY = "Weekly";
	public static final String FREQUENCYFORTNIGHTLY = "Fortnightly";
	public static final String FREQUENCYMONTHLY = "Monthly";
	public static final String FREQUENCYQUARTERLY = "Quarterly";
	public static final String FREQUENCYHALFYEARLY = "Half Yearly";
	public static final String FREQUENCYYEARLY = "Yearly";
	public static final String FREQUENCYBULLET = "Bullet";
	public static final String FREQUENCYTWICEAMONTH = "Twice a Month";
	public static final String CALENDARGREGORIANCALENDAR = "Gregorian Calendar";
	public static final String CALENDARHIJRICALENDAR = "Hijri Calendar";
	public static final String ONHOLIDAYNEXTDAY = "Next Day";
	public static final String ONHOLIDAYPREVIOUSDAY = "Previous Day";
	public static final String ONHOLIDAYSKIP = "Skip";
	public static final int [] DATEVALUES = {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31};
	public static final String DRAWINGPOWERINDICATORDERIVED = "Derived";
	public static final String DRAWINGPOWERINDICATOREQUAL = "Equal";
	public static final String DRAWINGPOWERINDICATORMAINTAINED = "Maintained";
	public static final String DRAWINGPOWERINDICATORPARENT = "Parent";
	public static final String UNDERDOCUMENTARYCREDITYES = "Yes";
	public static final String UNDERDOCUMENTARYCREDITNO = "No";
	public static final String ADDRESSTYPEBANKIDENTIFIER = "Bank Identifier";
	public static final String ADDRESSTYPENAMEANDADDRESS = "Name and Address";
	public static final String SWIFTADDRESSDETAILSYES = "yes";
	public static final String SWIFTADDRESSDETAILSNO = "no";
	public static final String BILLTENORSIGHT = "Sight";
	public static final String BILLTENORUSANCE = "Usance";
	public static final String BILLTYPESIGHT = "Sight";
	public static final String BILLTYPEUSANCE = "Usance";
	public static final String BILLTYPEMIXEDTENOR = "Mixed Tenor";
	public static final String ATTRIBUTETITLE = "title";
	public static final String ATTRIBUTEVALUE = "value";
}